POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "nama" : "Rosa Amalia",
    "email" : "rosaamalia@mail.com",
    "password" : "password",
    "username" : "rosaamalia",
    "telepon" : "0"
}

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "rosaamalia@mail.com",
    "password" : "password"
}